# Generated by Django 4.2.25 on 2025-11-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_bonus_end_date',
            field=models.DateField(default='2025-11-07', verbose_name='Bonus Campaign end date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_bonus_start_date',
            field=models.DateField(default='2025-11-07', verbose_name='Bonus Campaign start date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_end_date',
            field=models.DateField(default='2025-11-07', verbose_name='Campaign end date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_start_date',
            field=models.DateField(default='2025-11-07', verbose_name='Campaign start date'),
        ),
    ]
