# Generated by Django 4.2.25 on 2025-11-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_campaign_campaign_bonus_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_method_code',
            field=models.PositiveIntegerField(default=10, unique=True, verbose_name='Payment method type code'),
        ),
    ]
