# Generated by Django 4.2.25 on 2025-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_paymentmethod_payment_method_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_method_code',
            field=models.PositiveIntegerField(unique=True, verbose_name='Payment method type code'),
        ),
    ]
