# Generated by Django 4.2.25 on 2025-11-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_paymentmethod_payment_method_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_signature_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Signature description'),
        ),
    ]
