# Generated by Django 4.2.25 on 2025-11-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_campaign_campaign_bonus_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_bonus_end_date',
            field=models.DateField(default='2025-11-19', verbose_name='Bonus Campaign end date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_bonus_start_date',
            field=models.DateField(default='2025-11-19', verbose_name='Bonus Campaign start date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_end_date',
            field=models.DateField(default='2025-11-19', verbose_name='Campaign end date'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_start_date',
            field=models.DateField(default='2025-11-19', verbose_name='Campaign start date'),
        ),
    ]
